# Generated by Django 6.1.1 on 2026-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("explanation", models.TextField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("url", models.URLField()),
                ("hdurl", models.URLField(blank=True, null=True)),
                ("copyright", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "APOD entries",
                "ordering": ["-date"],
            },
        ),
    ]
